Repository wecode-bootcamp-korea/42-1st-Naweki-backend, pull requests merged in 2023-02, with the labels that each got.

#1 [Backend] 프로젝트 초기 셋팅.
  .env.sample
  .gitignore
  app.js
  package-lock.json
  package.json
  routes/index.js
Labels: 리뷰 진행 중

#2 [Backend] Add : db sql files.
  .gitignore
  app.js
  db/migrations/20230208041607_create_categories_table.sql
  db/migrations/20230208041937_create_order_status_table.sql
  db/migrations/20230208041957_create_users_table.sql
  db/migrations/20230208042028_create_sub_categories_table.sql
  db/migrations/20230208042107_create_products_table.sql
  db/migrations/20230208042108_create_sizes_table.sql
  db/migrations/20230208042109_create_colors_table.sql
  db/migrations/20230208042110_create_products_options_table.sql
  db/migrations/20230208042217_create_orders_table.sql
  db/migrations/20230208042252_create_shipping_address_table.sql
  db/migrations/20230208042318_create_order_items_table.sql
  db/migrations/20230208042328_create_reviews_table.sql
  db/migrations/20230208042346_create_products_images_table.sql
  db/migrations/20230208042358_create_gender_table.sql
  db/migrations/20230208042412_create_discount_season_sale_table.sql
  db/migrations/20230208042437_create_cart_table.sql
Labels: 멘토 리뷰 요청

#3 [42기 이한재] Add : 회원가입 API 구현
  .gitignore
  app.js
  classes/user.js
  controllers/userController.js
  db/migrations/20230208041957_create_users_table.sql
  models/index.js
  models/userDao.js
  routes/index.js
  routes/userRouter.js
  services/userService.js
  utils/error/globalErrMsg.js
  utils/error/handler.js
  utils/error/userErrMsg.js
  utils/validation.js
Labels: 멘토 리뷰 요청

#6 [42기 이한재] Modify : 컬럼명 오타 수정.
  db/migrations/20230208042110_create_products_options_table.sql
Labels: 멘토 리뷰 요청

#7 [42기 이한재] lookup API method POST 로 변경.
  routes/userRouter.js
Labels: 멘토 리뷰 요청

#8 [42기 이한재] Modify : country 컬럼 삭제.
  db/migrations/20230208041957_create_users_table.sql
Labels: 멘토 리뷰 요청

#5 [42기 강신혜] 로그인 기능 구현
  .gitignore
  .prettierrc
  app.js
  classes/user.js
  controllers/userController.js
  models/index.js
  models/userDao.js
  routes/index.js
  routes/userRouter.js
  services/userService.js
  utils/error/handler.js
  utils/error/userErrMsg.js
  utils/validation.js
Labels: 멘토 리뷰 요청

#10 [42기 이한재] Modify : order_items, order_status table 유니크 제약조건 수정.
  db/migrations/20230208041937_create_order_status_table.sql
  db/migrations/20230208042107_create_products_table.sql
  db/migrations/20230208042318_create_order_items_table.sql
Labels: 멘토 리뷰 요청

#9 [42기 이한재] Add : 상품목록 조회 API 구현.
  controllers/productController.js
  models/productDao.js
  routes/index.js
  routes/productRouter.js
  services/productService.js
  utils/error/handler.js
  utils/time.js
Labels: 멘토 리뷰 요청

#11 [42기 이한재] Modify : shipping_address country column 삭제.
  db/migrations/20230208041957_create_users_table.sql
  db/migrations/20230208042252_create_shipping_address_table.sql
  db/migrations/20230214080703_delete_country_colum_from_shipping_table.sql
Labels: 멘토 리뷰 요청

#13 [42기 강신혜] Modify : Colors 테이블 삭제, Products 테이블 컬럼 추가
  db/migrations/20230214124013_alter_products_options_table.sql
  db/migrations/20230214125715_delete_colors_table.sql
  db/migrations/20230214130016_add_color_column_products_table.sql
Labels: 멘토 리뷰 요청

#15 [42기 이한재] db 구조 변경에 따른 코드 수정.
  db/migrations/20230214133900_alter_cart_table.sql
  db/migrations/20230214134434_alter_products_table.sql
  db/migrations/20230214135405_alter_products_options_table.sql
  db/migrations/20230214135510_delete_genders_table.sql
  models/productDao.js
  services/productService.js
Labels: 멘토 리뷰 요청

#14 [42기 강신혜] Modify : Genders 테이블 삭제, Products 테이블 컬럼 추가
  db/migrations/20230214133900_alter_cart_table.sql
  db/migrations/20230214134434_alter_products_table.sql
  db/migrations/20230214135405_alter_products_options_table.sql
  db/migrations/20230214135510_delete_genders_table.sql
Labels: 멘토 리뷰 요청

#12 [42기 강신혜] Add: 상세페이지 조회 API 구현
  classes/product.js
  controllers/productController.js
  models/productDao.js
  package-lock.json
  package.json
  routes/productRouter.js
  services/productService.js
  utils/error/userErrMsg.js
Labels: 멘토 리뷰 요청

#16 [42기 이한재] Modify : response 필드값 camelCase 로 수정 & test 코드 삭제.
  controllers/productController.js
  models/productDao.js
  routes/productRouter.js
  services/productService.js
Labels: 멘토 리뷰 요청

#17 [42기 이한재] Modify : orders 테이블 order_status_code_id -> order_status_id…
  db/migrations/20230215050649_alter_table_orders_add_foreign_key.sql
Labels: 멘토 리뷰 요청

#18 [42기 강신혜] DB 업데이트에 따른 SQL 쿼리문 수정
  models/productDao.js
Labels: 멘토 리뷰 요청

#20 [42기 이한재] Modify : UUID 저장이 안되어서 order_number 길이 변경.
  db/migrations/20230215063521_alter_table_orders_modify_uuid.sql
Labels: 멘토 리뷰 요청

#19 [42기 강신혜] MODIFY: Cart 테이블 제약조건 추가
  db/migrations/20230215043557_alter_cart_table.sql
Labels: 멘토 리뷰 요청

#23 [42기 이한재] Modify : 색상별 분류 기능 추가 및 불필요한 코드 삭제.
  .gitignore
  app.js
  controllers/productController.js
  models/productDao.js
  services/productService.js
  utils/constants.js
Labels: 멘토 리뷰 요청

#21 [42기 이한재] Add : 장바구니 기능 구현.
  classes/address.js
  classes/orderQueryBuilder.js
  classes/user.js
  controllers/orderController.js
  controllers/userController.js
  middlewares/auth.js
  models/orderDao.js
  models/userDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/orderRouter.js
  routes/userRouter.js
  services/orderService.js
  services/userService.js
  utils/enum.js
  utils/error/globalErrMsg.js
  utils/error/handler.js
  utils/error/userErrMsg.js
  utils/paymentsMethod.js
  utils/utils.js
Labels: 멘토 리뷰 요청

#25 [42기 이한재] Modify : 주문하기 기능 구현 및 에러 메세지 처리 추가.
  controllers/orderController.js
  models/orderDao.js
  utils/error/handler.js
Labels: 수정 요청

#26 [42기 이한재] Modify : paymentAmount 로직 수정.
  models/orderDao.js
Labels: 멘토 리뷰 요청

#27 [42기 이한재] Modify : 에러 메세지 추가.
  classes/user.js
  models/orderDao.js
  models/userDao.js
  utils/error/globalErrMsg.js
  utils/error/handler.js
Labels: 멘토 리뷰 요청

#28 [42기 강신혜] MODIFY: 상세페이지 이미지 URL 코드 수정
  models/productDao.js
Labels: 멘토 리뷰 요청
